FROM centos:latest
MAINTAINER Mikhail Shubin

RUN yum install -y epel-release && \
	yum install -y python34 python34-pip python34-devel uwsgi uwsgi-plugin-python3 git gcc gcc-c++ make && \
	yum clean all && \
	rm -rf /var/cache/yum

ADD ./ /app
WORKDIR /app

RUN pip3 install -r requirements.txt --no-cache-dir

VOLUME [ "/app/data", "/app/conf/minter.conf" ]

# start app
CMD [ "/usr/sbin/uwsgi", \
	"--http-socket", ":8000", \
	"--master", \
	"--plugin", "python3", \
	"--mount", "/minter-service=/app/bin/wsgi_app.py", "--callable", "app", \
	"--uid", "uwsgi", "--gid", "uwsgi", \
	"--die-on-term", \
	"--processes", "10", \
	"--stats", "localhost:8001" ]

