FROM centos:latest
MAINTAINER Mikhail Shubin

RUN yum install -y epel-release && \
	yum install -y python34 python34-pip python34-devel git gcc gcc-c++ make nodejs nodejs-devel npm && \
	yum clean all && \
	rm -rf /var/cache/yum

ADD ./ /app
WORKDIR /app

RUN pip3 install -r requirements.txt --no-cache-dir

RUN npm install -g truffle ganache-cli && npm install --prefix /app zeppelin-solidity

VOLUME "/app/data"

CMD [ "./bin/test_wrapper.sh" ]

